compras = ('Canetas', 2, 'Roupas', 50, 'Teclado', 70, 'Computador', 5000, 'Geladeira', 4000)
print ('-' * 60)
print (f'{"LISTAGEM DE PREÇOS":.^40}')
print (f'{compras[0]:.<30}', end = ' ')
print (f'R$ {compras[1]}')
print (f'{compras[2]:.<30}', end = ' ')
print (f'R$ {compras[3]}')
print (f'{compras[4]:.<30}', end = ' ')
print (f'R$ {compras[5]}')
print (f'{compras[6]:.<30}', end = ' ')
print (f'R$ {compras [7]}')
print (f'{compras[8]:.<30}', end = ' ')
print (f'R$ {compras[9]}')