n= int (input ('Digite um numero com até 4 casas decimais: '))
u= (n // 1 % 10)
d= (n // 10 % 10)
c= (n // 100 % 10)
m= (n // 1000 % 10)
print ('Unidades: {}'.format(u))
print ('Dezenas: {}'.format(d))
print ('Centenas: {}'.format(c))
print ('Milhar: {}'.format(m))
